### ISSUE TITLE
GENIE deletes operating system

### ISSUE THREAD

**Issue by arguelles** [GENIE-MC/Generator#116]
When doing make cleandist, GENIE decides to, to first order, delete the OS.
![Captura de Pantalla 2020-10-04 a la(s) 10 32 42 a  m](https://user-images.githubusercontent.com/7256191/95018708-58530f00-062f-11eb-83e6-fdbbae02eafc.png)

**Comment by tamasgal** [comment]
This issue probably deserves a bit more attention 😉

**Comment by tamasgal** [comment]
This is the line which will operate on the root filesystem level when some variables are emtpy: https://github.com/GENIE-MC/Generator/blob/0b80f5ca6b315f5f7138c0fdf60ce40a4997697c/src/make/Make.std-package-targets#L172
