### ISSUE TITLE
full implementation of DCC 

### ISSUE THREAD

**Issue by dytman** [GENIE-MC/Generator#147]
DCC (Kamano, Nakamura, Lee, and Sato and others) generated a resonance+background model that works consistently for meson-nucleon, electron-nucleon, and neutrino-nucleon.  They published a series of papers, here's the summary for all but neutrino: https://inspirehep.net/literature/1756287.   I've been working on piN->piN, etaN, and K+Lambda for a start and Harry Lee was very helpful.  I've also discussed implementation of neutrino model and Toru Sato, also helpful.  This is independent of nuclear model but will full implementation will give us a consistent model for all fundamental principal and FSI interactions.

**Comment by candreop** [comment]
This is now a recorded project
