### ISSUE TITLE
Missing function implementation

### ISSUE THREAD

**Issue by mroda88** [GENIE-MC/Generator#168]
Julia found that this function is not implemented anywhere. Can we remove it?
https://github.com/GENIE-MC/Generator/blob/20dc2919afae1751b5ddd71e93b71e727afd1125/src/Physics/Multinucleon/EventGen/MECGenerator.h#L67

**Comment by sjgardiner** [comment]
Good catch, @jtenavidal and @mroda88! That function is now called `genie::utils::mec::GetMaxXSecTlctl` and is defined in `src/Physics/Multinucleon/XSection/MECUtils.cxx`. I simply forgot to remove the old declaration from the `MECGenerator` header file.

**Comment by mroda88** [comment]
@sjgardiner I'll do the removing.
