### ISSUE TITLE
GHEPUtils converts to NEUT mode with hard-coded WCut

### ISSUE THREAD

**Issue by luketpickering** [GENIE-MC/Generator#17]
W cut is hard coded [here](https://github.com/GENIE-MC/Generator/blob/master/src/Framework/GHEP/GHepUtils.cxx#L66)

Which doesn't correspond to the cut used in the transition region which is retrieved at runtime from e.g. [here](https://github.com/GENIE-MC/Generator/blob/master/config/G18_02a/G18_02a_02_11a/CommonParameters.xml#L87)

**Comment by mroda88** [comment]
fixed
