### ISSUE TITLE
Is it possible to store the seed in the ghep file?

### ISSUE THREAD

**Issue by mroda88** [GENIE-MC/Generator#172]
While debugging something with Stephen Dolan, we realised it would be nice to have the seed used to generate a file to be stored in the `ghep` file. No idea how at the moment, but if someone has ideas, I'm happy to attempt it.

**Comment by candreop** [comment]
@mroda88 add it in NtpMCJobConfig or NtpMCJobEnv (see Franework/Ntuple)

**Comment by mroda88** [comment]
I'll have a look this week hopefully, thanks @candreop !

**Comment by mroda88** [comment]
I had a look. It seemed that the NtpMCJobConfig was related to configurations from  the various models. Since the run number is already stored in the NtpHeader, I thought it was better if I added it there. 

PR #173 contains the fix. Comments are welcome
