### ISSUE TITLE
Refusing to exceed validity range: Emax = 1000

### ISSUE THREAD

**Issue by chy-learn** [GENIE-MC/Generator#268]
I'm trying to generate neutrino cross sections with energies higher than 1000GeV, but the simulations don't work.it told me that "Refusing to exceed validity range: Emax = 1000".
I use this "gmkspl -p 14 -t 1000080160 -n 150 -e 10000000".  It also told me that "No splines for tune G18_02a_00_000 were found!"
Can someone tell me what's wrong with this?

**Comment by mroda88** [comment]
Hi. Our configurations have a limited validity range: outside this range the consistency of the models is not guaranteed.

If you want to generate events at those energies, we recommend you use one of the VHE tunes. 
On the other hand, if you want to force the code to work at higher energy, you have to change the validity from the configuration files. Specifically, the configuration that controls the validity range is in `CommonParam.xml`, https://github.com/GENIE-MC/Generator/blob/00f0a27d443d332e6950f0339945ec4d9575e612/config/CommonParam.xml#L354
