### ISSUE TITLE
 Assertion `fUseSplines' failed

### ISSUE THREAD

**Issue by chy-learn** [GENIE-MC/Generator#272]
Hi,I have a strange problem.I used GHE19_00b tune to generate the cross-section data beforehand. When I try to use " gevgen -n 100 -e 100000 -p 14 -cross-sections ./xsec_all.xml --seed 171872 -t 1000080160[0.48],1000060120[0.12],1000200400[0.4] --tune GHE19_00b_00_000"
I got this "gevgen: GEVGDriver.cxx:456: void genie::GEVGDriver::CreateXSecSumSpline(int, double, double, bool): Assertion `fUseSplines' failed"
But I've already verified that the cross section data for the three elements already exists.Why are errors reported?

**Comment by lEuT01** [comment]
Hi, did you find a solution?

**Comment by chy-learn** [comment]
> Hi, did you find a solution?
change "-cross-sections" to "--cross-sections" ,this is written incorrectly in the user manual.
