### ISSUE TITLE
`Cache::Save()` passes wrong arguments to `TList::Write()`

### ISSUE THREAD

**Issue by PetrilloAtWork** [GENIE-MC/Generator#3]
GNU GCC 7.3.0 compiler reports:
~~~~
Cache.cxx: In member function ‘void genie::Cache::Save()’:
Cache.cxx:186:57: warning: enum constant in boolean context [-Wint-in-bool-context]
   keys->Write("key_list", TObject::kSingleKey&&TObject::kOverwrite);
                                                         ^~~~~~~~~~
~~~~
https://github.com/GENIE-MC/Generator/blob/cf98cb6ebd44fe5ae22b05d648a22bac7fcb9393/src/Framework/Utils/Cache.cxx#L186

The second argument should be a bit mask; I suppose the intention was to have `TObject::kSingleKey | TObject::kOverwrite` (use a single key and overwrite it as needed).
The `&&` operator makes teh expression a boolean (`1 && 2`), that is equivalent to `1`, that is just `TObject::kSingleKey`, and no overwrite.

**Comment by mroda88** [comment]
Fixed, thank you for the catch!
