### ISSUE TITLE
Apparent energy conservation issue for MEC events when G4 FSI model is used

### ISSUE THREAD

**Issue by wilkinson-nu** [GENIE-MC/Generator#313]
I'll preface this by saying this is an issue I saw with v3.2.0 with G18_10*_00_000 tunes, but failed to report properly. Some studies Richie showed in the context of DUNE using the new AR23_20i_00_000 model, but playing with the FSI model prompted me to check again.

The plots below are using files Richie made and put on the DUNE gpvms and converted to GST format, which can be found here: /pnfs/dune/persistent/users/rdiurba/DUNEND_FHC_numu_gst/, just in case anybody wants to check.

Looking at the total kinetic energy of protons and neutrons (labelled Ehad here) from CCMEC events vs true q0 (Enu - Elep) for the hA2018 FSI model (AR23_20i_00_000), you get a plot that looks sensible:
![image](https://github.com/GENIE-MC/Generator/assets/40141012/b19a79db-d963-4975-a509-9d8213bc2936)
This makes sense to me, there's some smearing due to the initial state nucleon momentum, but ignoring that, Ehad < q0. If anybody wants to reproduce these plots, you can probably guess the TTree draw command from the histogram title.

With the G4 FSI model (labelled AR23_20l_00_000 in Richie's files, which may be the usual convention, I'm not 100% sure):
![image](https://github.com/GENIE-MC/Generator/assets/40141012/bf8dcc61-76c4-43a9-8364-b8588f569d8b)
The obvious second population doesn't make sense to me, and looks like an energy conservation issue, although presumably there's a more subtle issue, it just looks like that.

I haven't poked into this in any more detail, so apologies for this slightly unhelpful issue report... I just wanted to flag this up.

**Comment by mroda88** [comment]
Hi, thanks for the report. We are investigating a number of issues related to G4 and INCL++ actually, and I think this is somehow related to those issues. I agree with you that for now those FSI should not be used for production.

**Comment by mroda88** [comment]
The fix should be in #360

**Comment by wilkinson-nu** [comment]
I finally got around the checking the update, and it does indeed seem to have resolved this issue, so I'll close it now. Thanks!
