### ISSUE TITLE
Code style: using directive at global scope

### ISSUE THREAD

**Issue by PetrilloAtWork** [GENIE-MC/Generator#32]
An unrequested coding style suggestion for your consideration:

https://github.com/GENIE-MC/Generator/blob/e7b305cfa8de3724a5bd0e6255e6a991ea39d9a1/src/Physics/HadronTransport/INukeHadroFates.h#L25-L29

Please do not import symbols in the global namespace from a header: this sets a `::string` symbol in every program that includes your header, and in every program where any included header includes this one directly or indirectly.

If you don't like prefixing each `string` with `std::`, you can still import the symbol from _within_ `genie` namespace, so that the effect is limited in scope.
This restriction also does not apply to source code (e.g. `.cxx` files), but rather only to headers.

**Comment by mroda88** [comment]
thanks Gianluca. We usually don't do it. That must have passed my radar. :-)

**Comment by mroda88** [comment]
I fixed that specific one. So I'm closing this issue. If you spot something else, please do tell us.
