### ISSUE TITLE
gspl2root is not useful for IBD  v3.04

### ISSUE THREAD

**Issue by WentaiLuo** [GENIE-MC/Generator#326]
![631404eab3d2495edf9205508059d40](https://github.com/GENIE-MC/Generator/assets/61787337/4b585e00-37e6-4656-bbda-ca56d91f400d)
![2fcaca7598388ae3dd27df0110fdc67](https://github.com/GENIE-MC/Generator/assets/61787337/14d15a02-0769-43d7-bf37-a90b15cb971e)
Hello, 
the version of genie I'm using is 3.04.
I have used gmkspl to generate cross section data for nue-bar  with H1 in the energy interval 0.001-0.6 GeV
However when I convert the cross section data into a root file using gspl2root, it prompts that the IBD cannot be found. attached  is the problem and the command line to use gspl2root. May I know how to solve it?

**Comment by candreop** [comment]
Thanks for reporting this, Wentai.  It is probably a quick fix.
if you edit https://github.com/GENIE-MC/Generator/blob/master/src/Apps/gSplineXml2Root.cxx, go somewhere just after line 610, and add
`else if (proc.IsInverseBetaDecay()  ) { title << "ibd"; }'
a TGraph would be created for that process and added to the output ROOT file.

I seem to think that's the only change that is required. Then, the graph should be added automatically when graphs for the total cross-section are constructed, but please do verify this.

Please can you submit a pull request if you have a validated fix?

**Comment by WentaiLuo** [comment]
> Thanks for reporting this, Wentai. It is probably a quick fix. if you edit https://github.com/GENIE-MC/Generator/blob/master/src/Apps/gSplineXml2Root.cxx, go somewhere just after line 610, and add `else if (proc.IsInverseBetaDecay() ) { title << "ibd"; }' a TGraph would be created for that process and added to the output ROOT file.
> 
> I seem to think that's the only change that is required. Then, the graph should be added automatically when graphs for the total cross-section are constructed, but please do verify this.
> 
> Please can you submit a pull request if you have a validated fix?

Thank you brother! You're too nice!
After adding that line of code, recompiling Genie generated ibd successfully, thanks so much!

**Comment by WentaiLuo** [comment]
> Thanks for reporting this, Wentai. It is probably a quick fix. if you edit https://github.com/GENIE-MC/Generator/blob/master/src/Apps/gSplineXml2Root.cxx, go somewhere just after line 610, and add `else if (proc.IsInverseBetaDecay() ) { title << "ibd"; }' a TGraph would be created for that process and added to the output ROOT file.
> 
> I seem to think that's the only change that is required. Then, the graph should be added automatically when graphs for the total cross-section are constructed, but please do verify this.
> 
> Please can you submit a pull request if you have a validated fix?
When you come to Beijing, I'll treat you to dinner!

**Comment by WentaiLuo** [comment]
> Thanks for reporting this, Wentai. It is probably a quick fix. if you edit https://github.com/GENIE-MC/Generator/blob/master/src/Apps/gSplineXml2Root.cxx, go somewhere just after line 610, and add `else if (proc.IsInverseBetaDecay() ) { title << "ibd"; }' a TGraph would be created for that process and added to the output ROOT file.
> 
> I seem to think that's the only change that is required. Then, the graph should be added automatically when graphs for the total cross-section are constructed, but please do verify this.
> 
> Please can you submit a pull request if you have a validated fix?

After fix all problems, I will submit a pull request! Another issue is open……
