### ISSUE TITLE
Remove new Q2 limit for electron scattering which cuts into physical space

### ISSUE THREAD

**Issue by candreop** [GENIE-MC/Generator#4]
The new kMinQ2Limit_e is a hack aimed at improving CPU efficiency for certain comparisons against electron scattering data. However the built-in limits are not meant to cut into the allowed phase space in any importany way, but merely to protect againt infinities.

kMinQ2Limit_e was installed on the understanding that it is a stopgap and that a new method will be developed for user-specified kinematic limits to be supplied via the GENIE configuration system.

The stopgap implementation can not be what we are permanenlty left with, so the plan should be to remove kMinQ2Limit_e before the release of GENIE 3.2.0.

**Comment by dytman** [comment]
not an issue, nothing was implemented in v3.0.0.  Goal is to have this implemented properly for v3.2.  Elec scat can't run without a reasonable Q2min which is different than for neutrinos.  Our studies show a single value works most of the time.
