### ISSUE TITLE
Error when using gntpc with new version of GENIE

### ISSUE THREAD

**Issue by AlMuOv** [GENIE-MC/Generator#403]
Greetings, I have installed the new version of GENIE (3.4.2) and when using gntpc to switch from a ghep.root format to gst.root 

`gntpc -i File.ghep.root -f gst`

I get the error

```
1714073415 ERROR AlgConfigPool : [s] <LoadRegistries (295)> : The XML doc doesn't exist! (filename : MArunAxialFormFactorModel.xml)
1714073415 ERROR AlgConfigPool : [s] <LoadAlgConfig (141)> : Error in loading config sets for algorithm = genie::MArunAxialFormFactorModel
```

**Comment by mroda88** [comment]
Hi, I think you are reporting the wrong version. The tag v3.4.2 does not contain `MArunAxialFormFactorModel`, that is only for the master. Do you see the problem in the master?

**Comment by mroda88** [comment]
In fact, after your report I checked, and you should see the problem in the master, not in the tagged version. The master will be fixed soon.

**Comment by AlMuOv** [comment]
It was, sorry

**Comment by mroda88** [comment]
Fixed with https://github.com/GENIE-MC/Generator/pull/405
