### ISSUE TITLE
Time associated with vertex assumes speed of light

### ISSUE THREAD

**Issue by PetrilloAtWork** [GENIE-MC/Generator#6]
A possible improvement for your consideration:

https://github.com/GENIE-MC/Generator/blob/7df848a53fec960cccf3de1307f78cac1034c7b1/src/Framework/EventGen/GMCJDriver.cxx#L1254

If I understand this right, this assumes that the incident particle, which the flux deposited at `x4`, has travelled to `vtx` at the speed of light. This may be problematic for massive particles (like dark matter), which might take their good time to get there. Given that the method has also `p4` available, it should be possible to use the correct speed of the incident particle.

**Comment by candreop** [comment]
Thanks Gianluca. This is a good suggestion. It is something we neglected once we started simulating more massive particles. I will do the correction asap.
