### ISSUE TITLE
GHepUtils NEUT Mode converter doesn't handle new diffractive mode

### ISSUE THREAD

**Issue by luketpickering** [GENIE-MC/Generator#84]
The GHepUtils NEUT mode converter returns mode 0 for diffractive events, it should return 15/-15 for CCDFR from a neutrino/anti-neutrino and 35/-35 for NCDFR.

**Comment by nusense** [comment]
Both this an NuanceReactionCode translator need to be revisited for completeness and coverage

https://cdcvs.fnal.gov/redmine/issues/18025
