### ISSUE TITLE
git diff in GVersion.h

### ISSUE THREAD

**Issue by mroda88** [GENIE-MC/Generator#9]
The creation of GVersion.h is faulted. 
the piece of code `if ($git_revision ne "-1" ) {
  $git_differences = `git diff HEAD`;
  if($? == 0) {
    print GVRS "/* \n";
    print GVRS " * git differences at compile time: \n";
    print GVRS "$git_differences";
    print GVRS "*/ \n\n";
  }
}`
from src/scripts/setup/genie-write-gversion - line 84 is creating a file which can potentially not compile if the changes involves the character `*/` Afro just experienced this.
I suggest to remove these lines. We have git to keep track of the changes, no point in having this in an header. 
@sjgardiner you had a look at this code recently. Is it ok?

**Comment by sjgardiner** [comment]
Ouch, that `*/` issue is a nasty one. Given how fragile it is, I support removing the `$git_differences` stuff.
