### ISSUE TITLE
Adding Tungsten cross-section to the pre-generated splines

### ISSUE THREAD

**Issue by andrea-celentano** [GENIE-MC/Generator#99]
I'd like to ask to the GENIE developers if it possible to include splines for Tungsten in the set of pre-generated splines - i.e. those that can be found here: http://scisoft.fnal.gov/scisoft/packages/genie_xsec/

For Tungsten, the relevant isotopes to add are 

182W  --> 1000821820
183W  --> 1000821830
184W  --> 1000821840
186W  --> 1000821860

**Comment by nusense** [comment]
I had a similar request back at the end of November and updated the generation script to include the following (PDG, Symbol, natural abundance, reduced=appears in "small" file):
``` ### tungsten
  1000741800  W180      0.12
  1000741820  W182     26.5
  1000741830  W183     14.31
  1000741840  W184     30.64     reduced
  1000741860  W186     28.43
```
also
```
 ### gold
  1000791970 Au197    100.       reduced
```
I'm afraid they didn't make it into the v3_00_06 iteration.  These will take effect next production run.

If the need is imminent, perhaps I can run a particular tune or two for you / your experiment (which is?).  I'm not enthralled with the idea of running 15 though :-)

Do you actually desire all 4 of the major components to appear in the "small" file?  Does your geometry actually use a mixture of these four, or just the "average" (W184)?

**Comment by andrea-celentano** [comment]
Dear Robert,
good to see this request is interesting also for other people. I am using natural W composition, hence the 5 that you listed. I think it would be ok if W184 is in the "small" file, and all the others in the big one. If you can run W184 for me while waiting for all the others, that would be great! When you do so, are you going to produce a single cross-section file with ALL the targets together, i.e. the "original" ones plus another with W184?

PS: I am currently working in the BDX experiment (https://arxiv.org/abs/1910.03532) - a proposed electron beam-dump experiment at JLab searching for Light Dark Matter. For us, neutrinos are a background!

**Comment by nusense** [comment]
The script I work from makes use of the parallelism of the grid, but factorizes things along the lines of:

1. { each of 6 nu flavors} x { proton, neutron}, i.e. 12 jobs
2. sum to make a gxspl-freenuc.xml.gz
3. { each of 6 nu flavors} x { each isotope}, ~700+ jobs
4. sum to make  gxspl-NUbig.xml, pare down to make gxspl-NUsmall.xml
5. misc + package up everything into a tarball

I think this version also picks up a change in the file naming (re: gxspl-FNALbig.xml) :  FNAL->NU, to allow for distinguishing future alternative of GENIE's electron scattering, but with symlinks for backward compatibility.

Alas, I don't really have a provision for just running one isotope (even now the script is dangerously complex, adding the ability to bootstrap off a previous run isn't so triivial), so I'm willing to burn some CPU to get an expanded file but regenerating some things that already exist.   But for which tune?   The default, `G18_02a_00_000` ?

**Comment by andrea-celentano** [comment]
Yes, the default tune is fine! G18_02a_00_000

**Comment by nusense** [comment]
Okay, the default tune splines are done and available at:

```
https://scisoft.fnal.gov/scisoft/packages/genie_xsec/v3_00_06a/
       genie_xsec-3.00.06a-noarch-G1802a00000-k250-e1000.tar.bz2
```

Total turn around time < 24hr !

**Comment by andrea-celentano** [comment]
Dear Robert,
thanks, great!!!

**Comment by nusense** [comment]
closing old, completed issue
